### ISSUE TITLE
how to use mailspring-keybase plugin?

### ISSUE THREAD

**Issue by valentt** [NgoHuy/mailspring-keybase#3]
Hi NgoHuy,
getting pgp to work with Mailspring is an awesome feature, and thank you for your work.

I have installed this plugin but I don't see anyway how to use it. Where and how can I add my pgp key? I don't see any button to encrypt email.

I'm on Fedora Linux 28 if that helps.

Thanks,
Valent.

**Comment by NgoHuy** [comment]
please see #2 for more info
