### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by asddsaz** [NgoHuy/mailspring-keybase#5]
This packages does not have a license file.
Can you add a LICENSE file?

I recommend [MIT](https://en.wikipedia.org/wiki/MIT_License), [BSD](https://en.wikipedia.org/wiki/BSD_licenses), or [CC0](https://choosealicense.com/licenses/cc0-1.0/) for the license type.

**Comment by NgoHuy** [comment]
Thank for your suggestion, but license is belong to Nilas mail :)

**Comment by NgoHuy** [comment]
I just review Nylas's plugins license and add it as https://github.com/NgoHuy/mailspring-keybase/commit/bff88df3685d273453857a143230b5e724b1e849
