### ISSUE TITLE
Add install instructions in Readme.md

### ISSUE THREAD

**Issue by daxid** [NgoHuy/mailspring-keybase#7]
Hi,

Installation is not trivial.
Instructions should be put in Readme.md

For instance : 

* clone repository into any location
* `cd /path/to/mailspring-keybase` and then `npm install`
* start Mailspring and add plugin - you should see a success notification
* close Mailspring and edit `config.json` and remove `keybase` from disabled plugins list (config.json can be found in different places depending on your OS. Search for the `Mailspring` folder in your filesystem)
* start Mailspring, key management can be found in preferences

Best regards
--
David

**Comment by guizmoau** [comment]
following those instructions but I can't get any features
on debian stretch

**Comment by NgoHuy** [comment]
I merged the pull request as #9 
Please testing it on your environment
