### ISSUE TITLE
Does not work on Manjaro 18 and Mailspring 1.7.2

### ISSUE THREAD

**Issue by klention** [NgoHuy/mailspring-keybase#8]
Hi,

I am trying to configure this plugins using this steps but it doesn't seams to work. Can not find a Encryption tab on Preference.

1. stop all Mailspring processes
2. clone repository into any location
3. cd /path/to/mailspring-keybase and then npm install
4. start Mailspring and add plugin - you should see a success notification
5. close Mailspring and edit config.json and remove keybase from disabled plugins list
6. start Mailspring, key management can be found in preferences

**Comment by NgoHuy** [comment]
new mailspring uses new plugin's spec, I didnot use mailspring for a long time, but I will recheck it at weekend.

**Comment by NgoHuy** [comment]
New modules switched to typescripts, I will convert it to typescripts

**Comment by klention** [comment]
Hi there.
Did you find the time to take a look?
Also if you could would be great to show the steps taken to get this plugin work. 
Regards

**Comment by NgoHuy** [comment]
I'm busy, but I will recheck it soon,
